language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  app: myrecipesapi
  api_key:
    secure: Q2Zu3M8RLUj7u63K2emYaJr5Wt7k5pGsaAfaQiMHa2Cr/BKTt81KskRy26/KU05DfZUNkHD33q9gyU0QLEpB8cX9RHP7JGSMi+bpg4XLn18TzTw9+osWxFhm1tcutzCUaKSGUUAvLkRe54tWEg32uxH41A97KtyrAWVfrljU58gCDz/qrr0gMkgfN3oxq+6dYXR2gcS/MAJxOv4lT/oHxTnOBpitTrtVGEcVHbV99sdWS9UBJrrynJJ12DppSlwlA+JhiuGByrjBgFpKFiUJkxmY8C2/sOiJjOjG7QlqHQIVAPqCTXOb36MV4GVwF7LMGq68jIX5S12eoJHrjL5F2Xy3smjR95NJceSiHcAP64N+FVsHMQjfINH9dmGz1wnOdRZXqC5nJBQrPrcxf6s/UVhEpBxzE9o4sJaYKPxtt4Jt+1r0aF8zthUxp8oIdHI3tynA6lgMmt1dhR15B03awiP4ApUw87SwY0uglI1tvE61VyRr7+clDpv87HVA7UFUZnzi2MSYkU9M2N223GlPd7Cx4F6NuJOz0gBwCBmFAH9eter3R4zncq71hd307WBmOya4nbDrQyr9T60GNYOoSLWwIQ8OzmJyo2HYmekgj5gmUL7WRru39idQxVgBmx06V8lgAy3nY6by2u5lDLAXw6TSLj4F0EzecrPi9uqaXX8=