version: '2'
services:
  db:
    container_name: myrecipespg
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: recipes
    volumes:
      - myrecipes_localdb:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  myrecipes_localdb:
